version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bible-backend
    ports:
      - "8080:8080"
    volumes:
      - ./Bible:/Bible:ro
      - ./data:/root/data
    environment:
      - CGO_ENABLED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bible-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
